<?php

define('SPS_CONFIG_ROOT_CONDITION', "root_condition_settings");
define('SPS_CONFIG_PLUGIN_CONTROLLER', "plugin_controller_settings");
define('SPS_CONFIG_HOOK_CONTROLLER', "hook_controller_settings");
define('SPS_CONFIG_STATE_CONTROLLER', "state_controller_settings");
define('SPS_CONFIG_SITESTATE', "sitestate_settings");
define('SPS_CONFIG_OVERRIDE_CONTROLLERS', "override_controllers_settings");
define('SPS_CONFIG_PREFIX', "sps_config");
define('SPS_NO_ALTER_QUERY_TAG', "sps_no_alter");


/**
 *  Implements hook_sps_plugin_types()
 */
function sps_sps_plugin_types() {
  return array(
    'reaction' => array(
      'interface' => 'Drupal\sps\Plugins\ReactionInterface',
      'defaults' => array(
        'instance_settings' => array(),
      ),
      'requires' => array(
        'class' => TRUE,
      ),
    ),
    'override_controller' => array(
      'interface' => 'Drupal\sps\Plugins\OverrideControllerInterface',
      'defaults' => array(
        'instance_settings' => array(),
      ),
      'requires' => array(
        'class' => TRUE,
        'implements_controller_api' => TRUE,
      ),
    ),
    'override' => array(
      'interface' => 'Drupal\sps\Plugins\OverrideInterface',
      'defaults' => array(
        'instance_settings' => array(),
      ),
      'requires' => array(
        'condition' => TRUE,
      ),
    ),
    'condition' => array(
      'interface' => 'Drupal\sps\Plugins\ConditionInterface',
      'defaults' => array(
        'class' => 'Drupal\sps\Plugins\Condition\BasicCondition',
        'instance_settings' => array(),
      ),
      'requires' => array(
      ),
    ),
    'widget' => array(
      'interface' => 'Drupal\sps\Plugins\WidgetInterface',
      'defaults' => array(
        'class' => 'Drupal\sps\Plugins\Widget\Widget',
        'instance_settings' => array(),
      ),
      'requires' => array(
      ),
    ),
  );
}

/**
 * Implements hook_hook_info().
 */
function sps_hook_info() {
  foreach(sps_sps_plugin_types() as $name => $type) {
    $hooks["sps_{$name}_plugins"] = array('group' => 'sps_plugins');
  }
  return $hooks;
}

/**
 * A form callback for use by drupal_get_form().
 *
 * When called like:
 * drupal_get_form('sps_condition_preview_form', array($this, 'getPreviewForm'))
 * by the manager or a condition, it will return that form.
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 *  A FAPI array for drupal_get_form if a callback is provided, or NULL
 *
 * @see \Drupal\sps\Manager::getPreviewForm();
 */
function sps_condition_preview_form($form, &$form_state) {
  drupal_add_css(drupal_get_path('module', 'sps').'/css/sps.css');

  if (!empty($form_state['build_info']['args'][0])) {
    $condition = $form_state['build_info']['args'][0];
    $form_state['root_condition'] = $condition;
    $form = $condition->getElement($form, $form_state);

    $form['Cancel'] = array(
      '#type' => 'submit',
      '#value' => 'Cancel',
    );

    $form['preview'] = array(
      '#type' => 'submit',
      '#value' => 'Preview',
    );

    $form['#prefix'] = '<div class="sps-preview-form clearfix">';
    $form['#suffix'] = '</div>';
    return $form;
  }
}

/**
 * A validate will find the root condition (from the build args)
 * and call its validateElement method
 *
 * also if we have a cancel selected we clear the site state
 *
 */
function sps_condition_preview_form_validate($form, &$form_state) {
  // if cancel was press blow away the site state and refresh
  if($form_state['clicked_button']['#id'] == 'edit-cancel') {
    sps_get_manager()->clearSiteState();
    drupal_goto(current_path());
  }
  if (!empty($form_state['build_info']['args'][0])) {
    $condition = $form_state['build_info']['args'][0];
    $form_state['root_condition'] = $condition;
    $condition->validateElement($form, $form_state);
  }
}

/**
 * A submit will find the root condition (from the build args)
 * and call its submitElement method
 *
 * Then the manager is notified that the submit happened.
 *
 */
function sps_condition_preview_form_submit($form, &$form_state) {

  if (!empty($form_state['build_info']['args'][0])) {
    $condition = $form_state['build_info']['args'][0];
    $form_state['root_condition'] = $condition;
    $condition->submitElement($form, $form_state);
    sps_get_manager()->previewFormSubmitted($condition);
  }
}

/**
 * Get the default Storage Controller
 *
 * @return \Drupal\sps\StorageController\DrupalVariableController
 */
function sps_get_default_config_controller() {
  $controller = &drupal_static(__FUNCTION__);

  if(!isset($controller)) {
    $controller = new \Drupal\sps\StorageController\DrupalVariableController(SPS_CONFIG_PREFIX);
  }
  return $controller;
}

/**
 * Get the default Manager
 *
 * @return \Drupal\sps\Manager
 */
function sps_get_manager() {
  $manager = &drupal_static(__FUNCTION__);

  if(!isset($manager)) {
    $manager = new \Drupal\sps\Manager(sps_get_default_config_controller());
  }

  return $manager;
}
/**
 * Implements hook_query_alter().
 *
 * This is done on behave of the node_select_query_alter reaction
 */
function sps_query_alter($query) {
  $data = new stdClass();
  $data->query=$query;
  sps_get_manager()->react('node_select_query_alter', $data);
}

/**
 * Implements hook_entity_info_alter().
 *
 * changing the node controller on behalf of the node_load Reaction
 */
function sps_entity_info_alter(&$entity_info) {
  $entity_info['node']['controller class'] = '\Drupal\sps\NodeController';
}

/**
 * Implements hook_iib_page_item().
 */
function sps_iib_page_item() {
  $manager = sps_get_manager();
  $preview_form = $manager->getPreviewForm();
  $items['left'] = array(
    '#weight' => -10,
    '#prefix' => '<div>',
    '#markup' => drupal_render($preview_form),
    '#suffix' => '</div>',
  );
  return $items;
}

/**
* This callback is used by the wrapper condition to change out which
* condition is being used
*
* @see \Drupal\sps\Plugins\Condition\WrapperCondition::getElement()
* @param $form
*   A drupal form array
* @param $form_state
*  A drupal form state array
* @return
*   a drupal render array
*/
function sps_wrapper_condition_ajax_callback($form, $form_state) {
  array_pop($form_state['triggering_element']['#parents']);
  foreach($form_state['triggering_element']['#parents'] as $key) {
    $form = $form[$key];
  }
  return $form;
}

/**
 * This is to assit in calling function outside of the sps
 * module that might have side effect. It allows for test to
 * change the function for there tests
 * the syntax to use is
 *
 * sps_drupal()->FUNCTIONNAME(Param1, Param2, Param3);
 * eg.g sps_drupal()->drupal_get_form('sps_preview_form');
 *
 * if a param needs to be passed by reference the following syntax can be used
 * sps_drupal()->ref[FUNCTIONNAME](Param1, Param2, Param3);
 * eg.g sps_drupal()->set('drupal_get_form','sps_preview_form');
 *
 * if a test need to reset that function it can run
 * sps->call['drupal_get_form'] = 'test_drupal_get_form';
 * and then if something called drupal_get_form it would call
 * test_drupal_get_form instead.
 */
function sps_drupal() {
  $drupal = &drupal_static(__FUNCTION__);
  if(!$drupal) {
    $drupal = new \Drupal\sps\Drupal();
  }
  return $drupal;
}

