<?php
/**
 * @file The Interactive Information Bar module provides an area at the top of rendered
 * entities for other modules to use to display admin information regarding
 * that entity.
 */

/**
 * Get the items to place into the IIB.
 *
 * To add items to this list a module should implement hook_iib_data($items)
 * and return a render array
 * The result of this hook invocation is alterable using hook_iib_data_alter().
 *
 * @see iib.api.php
 */
function iib_get_page_data() {
  if (iib_should_show_view()) {
    $items = array();
    module_invoke_all('iib_page_item', $items);
    drupal_alter('iib_page_item', $items);
    return $items;
  }
}

/**
 * Implements hook_iib_page_item().
 *
 * Add anything added by calling iib_set_data().
 */
function iib_iib_page_item(&$items) {
  $set_items = &drupal_static('iib_set_items', array());
  if (!empty($set_items)) {
    $items += $set_items;
  }
  drupal_static_reset('iib_set_items');
}


/**
 * Allows other modules to add items to the IIB.
 *
 * Calling this function and passing a renderable element will result
 * in that element getting appended to the Interactive Information Bar
 * at the page level.
 *
 * @param $renderable
 *  A renderable element (a render array) to be added to the IIB.
 *
 * @see iib.api.php
 */
function iib_set_item($renderable) {
  $items = &drupal_static('iib_set_items', array());
  $items[] = $renderable;
}

/**
 * Implements hook_entity_view().
 *
 * Provides a way for modules to add information to each entity being rendered
 * during a page load.  This function invokes hook_iib_entity_item().
 *
 * @see iib.api.php
 */
function iib_entity_view($entity, $type, $view_mode, $langcode) {
  if (iib_should_show_view()) {
    $items = array();
    module_invoke_all('iib_entity_item', $items, $entity, $type, $view_mode);
    drupal_alter('iib_entity_item', $items, $entity, $type, $view_mode);

    $entity->content['iib'] = iib_create_render_array($items);
  }
}

/**
 * A helper function to construct a render array from items.
 *
 * @param $items
 *  An array of renderable elements
 *
 * @return
 *  A render array containing the proper wrapping elements.
 */
function iib_create_render_array($items) {
  return array(
    '#prefix' => '<div class="iib">',
    'items' => $items,
    '#suffix' => '</div>',
    '#weight' => -100,
  );
}

/**
 * Check our configuration to see if we should show the iib for this
 * entity.
 *
 * @return
 *  A boolean representing whether or not the iib should be shown
 */
function iib_should_show_view() {
  return user_access('view interactive information bar');
}

/**
 * Implements hook_permission().
 *
 * Add a permission for viewing the interactive information bar
 */
function iib_permission() {
  return array(
    'view interactive information bar' => array(
      'title' => t('View Interactive Information Bar'),
      'description' => t('Allow users to view the IIB.  This may allow users to perform administrative tasks.'),
    ),
  );
}