<?php

define('SPS_CONFIG_ROOT_CONDITION', "root_condition_settings");
define('SPS_CONFIG_PREFIX', "sps_config");


/**
 * A form callback for use by drupal_get_form().
 *
 * When called like:
 * drupal_get_form('sps_condition_preview_form', array($this, 'getPreviewForm'))
 * by the manager or a condition, it will return that form.
 *
 * @return
 *  A FAPI array for drupal_get_form if a callback is provided, or NULL
 *
 * @see Manager::getPreviewForm();
 */
function sps_condition_preview_form($form, &$form_state) {
  if (!empty($form_state['build_info']['args'][0])) {
    $form_function = $form_state['build_info']['args'][0];
    if (is_callable($form_function)) {
      $form_function($form, $form_state);
    }
  }
}

/**
 * Get the default Storage Controller
 *
 * @return \Drupal\sps\StorageController\DrupalVariableController
 */
function sps_get_default_config_controller() {
  $controller = &drupal_static(__FUNCTION__);

  if(!isset($controller)) {
    $controller = new \Drupal\sps\StorageController\DrupalVariableController(SPS_CONFIG_PREFIX);
  }

  return $controller;
}

function sps_query_alter($query) {
 // $react = new \Drupal\sps\Plugins\Reaction\QueryAlterReaction(array("tables"=> array("base"=>"node", "revision"=>"node_revision")), "bpb");
//  $react->react($query);
}

function sps_init() {
  $query = db_select("node", 'b');
  $query->fields('b', array('title', 'status', 'promote', 'sticky'));
  $query->join("node_revision", "r", "r.vid = b.vid");
  dpm(\Drupal\sps\Test\QueryAlterable::exportConfig($query));
}
 

 
  
